global:
  smtp_from: 'themusama@gmail.com'
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: 'themusama@gmail.com'
  smtp_auth_identity: 'themusama@gmail.com'
  smtp_auth_password: 'gmail access id'

route:
  # fallback admin
  receiver: admin
  group_wait: 40s
  group_interval: 5m
  repeat_interval: 30m
  routes:
    #star solutions
    - match_re:
        app_type: (linux | windows)
      receiver: ss-admin
      routes:
      # linux team
      - match:
          app_type: linux
          #fallback receiver
        receiver: linux-team-admin
        routes:
        - match:
            severity: critical
          receiver: linux-team-manager
        - match:
            severity: warning
          receiver: linux-team-lead

    

      # windows team
      - match:
          app_type: windows
        # fallback receiver
        receiver: windows-team-admin
        routes:
          - match:
              severity: critical
            receiver: windows-team-manager
          - match:
              severity: warning
            receiver: windows-team-lead
    #PEC Technologies
    - match_re:
        app_labels: (python | go)
        #fallback receiver
      receiver: pec-admin
      routes:
        #python team
        - match:
            app_type: python
            #fallback receiver
          receiver: python-team-admin  
          routes:
            - match:
                severity: critical
              receiver: python-manager
            - match: 
                severity: warning
              receiver: python-team-lead
        #go team
        - match:
            app_type: go
          #fallback receiver
          receiver: go-team-admin
          routes:
            - match:
                severity: critical
              receiver: go-manager
            - match:
                severity: warning
              receiver: go-team-lead

inhibit_rules:
  - source_match: 
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['app_type', 'category']



        

receivers:
- name: admin
  email_configs:
  - to: 'usama345327@gmail.com'

- name: ss-admin
  email_configs:
  - to: ss-admin@example.com

- name: linux-team-admin
  email_configs:
  - to: linux-team-admin@example.com

- name: linux-team-manager
  email_configs:
  - to: linux-team-manager@example.com

- name: linux-team-lead
  email_configs:
  - to: linux-team-lead@example.com

- name: windows-team-admin
  email_configs:
  - to: windows-team-admin@example.com

- name: windows-team-manager
  email_configs:
  - to: windows-team-manager@example.com

- name: windows-team-lead
  email_configs:
  - to: windows-team-lead@example.com